from __future__ import annotations

from importlib import import_module
from typing import Any

_LAZY_EXPORTS = {
    'AnalysisCaseBuilder': ('geoai_simkit.pipeline.builder', 'AnalysisCaseBuilder'),
    'ExecutionPlan': ('geoai_simkit.pipeline.execution', 'ExecutionPlan'),
    'build_execution_plan': ('geoai_simkit.pipeline.execution', 'build_execution_plan'),
    'build_solver_settings': ('geoai_simkit.pipeline.execution', 'build_solver_settings'),
    'recommend_backend_route': ('geoai_simkit.pipeline.execution', 'recommend_backend_route'),
    'recommended_thread_count': ('geoai_simkit.pipeline.execution', 'recommended_thread_count'),
    'CASE_FILE_KIND': ('geoai_simkit.pipeline.io', 'CASE_FILE_KIND'),
    'CASE_FORMAT_VERSION': ('geoai_simkit.pipeline.io', 'CASE_FORMAT_VERSION'),
    'SUPPORTED_CASE_FORMAT_VERSIONS': ('geoai_simkit.pipeline.io', 'SUPPORTED_CASE_FORMAT_VERSIONS'),
    'case_spec_from_dict': ('geoai_simkit.pipeline.io', 'case_spec_from_dict'),
    'case_spec_to_dict': ('geoai_simkit.pipeline.io', 'case_spec_to_dict'),
    'load_case_spec': ('geoai_simkit.pipeline.io', 'load_case_spec'),
    'save_case_spec': ('geoai_simkit.pipeline.io', 'save_case_spec'),
    'build_node_pair_contact': ('geoai_simkit.pipeline.preprocess', 'build_node_pair_contact'),
    'build_stage_sequence_from_excavation': ('geoai_simkit.pipeline.preprocess', 'build_stage_sequence_from_excavation'),
    'resolve_boundary_condition_spec': ('geoai_simkit.pipeline.preprocess', 'resolve_boundary_condition_spec'),
    'resolve_excavation_steps': ('geoai_simkit.pipeline.preprocess', 'resolve_excavation_steps'),
    'resolve_load_spec': ('geoai_simkit.pipeline.preprocess', 'resolve_load_spec'),
    'resolve_stage_spec': ('geoai_simkit.pipeline.preprocess', 'resolve_stage_spec'),
    'PreprocessorArtifact': ('geoai_simkit.pipeline.preprocessor', 'PreprocessorArtifact'),
    'PreprocessorSnapshot': ('geoai_simkit.pipeline.preprocessor', 'PreprocessorSnapshot'),
    'build_preprocessor_snapshot': ('geoai_simkit.pipeline.preprocessor', 'build_preprocessor_snapshot'),
    'save_preprocessor_snapshot': ('geoai_simkit.pipeline.preprocessor', 'save_preprocessor_snapshot'),
    'AnalysisExportSpec': ('geoai_simkit.pipeline.runner', 'AnalysisExportSpec'),
    'AnalysisRunResult': ('geoai_simkit.pipeline.runner', 'AnalysisRunResult'),
    'AnalysisTaskSpec': ('geoai_simkit.pipeline.runner', 'AnalysisTaskSpec'),
    'GeneralFEMSolver': ('geoai_simkit.pipeline.runner', 'GeneralFEMSolver'),
    'CompileConfig': ('geoai_simkit.runtime', 'CompileConfig'),
    'RuntimeCompiler': ('geoai_simkit.runtime', 'RuntimeCompiler'),
    'RuntimeConfig': ('geoai_simkit.runtime', 'RuntimeConfig'),
    'SolverPolicy': ('geoai_simkit.runtime', 'SolverPolicy'),
    'collect_region_point_ids': ('geoai_simkit.pipeline.selectors', 'collect_region_point_ids'),
    'resolve_region_selector': ('geoai_simkit.pipeline.selectors', 'resolve_region_selector'),
    'union_region_names': ('geoai_simkit.pipeline.selectors', 'union_region_names'),
    'geometry_source_from_ifc': ('geoai_simkit.pipeline.sources', 'geometry_source_from_ifc'),
    'geometry_source_from_mesh': ('geoai_simkit.pipeline.sources', 'geometry_source_from_mesh'),
    'geometry_source_from_mesh_file': ('geoai_simkit.pipeline.sources', 'geometry_source_from_mesh_file'),
    'geometry_source_from_parametric_pit': ('geoai_simkit.pipeline.sources', 'geometry_source_from_parametric_pit'),
    'geometry_source_from_editable_blocks': ('geoai_simkit.pipeline.sources', 'geometry_source_from_editable_blocks'),
    'register_geometry_source': ('geoai_simkit.pipeline.sources', 'register_geometry_source'),
    'registered_geometry_sources': ('geoai_simkit.pipeline.sources', 'registered_geometry_sources'),
    'resolve_registered_geometry_source': ('geoai_simkit.pipeline.sources', 'resolve_registered_geometry_source'),
    'AnalysisCaseSpec': ('geoai_simkit.pipeline.specs', 'AnalysisCaseSpec'),
    'BoundaryConditionSpec': ('geoai_simkit.pipeline.specs', 'BoundaryConditionSpec'),
    'ContactPairSpec': ('geoai_simkit.pipeline.specs', 'ContactPairSpec'),
    'ExcavationStepSpec': ('geoai_simkit.pipeline.specs', 'ExcavationStepSpec'),
    'GeometrySource': ('geoai_simkit.pipeline.specs', 'GeometrySource'),
    'InterfaceGeneratorSpec': ('geoai_simkit.pipeline.specs', 'InterfaceGeneratorSpec'),
    'LoadSpec': ('geoai_simkit.pipeline.specs', 'LoadSpec'),
    'MaterialAssignmentSpec': ('geoai_simkit.pipeline.specs', 'MaterialAssignmentSpec'),
    'MeshAssemblySpec': ('geoai_simkit.pipeline.specs', 'MeshAssemblySpec'),
    'MeshPreparationSpec': ('geoai_simkit.pipeline.specs', 'MeshPreparationSpec'),
    'PreparedAnalysisCase': ('geoai_simkit.pipeline.specs', 'PreparedAnalysisCase'),
    'PreparationReport': ('geoai_simkit.pipeline.specs', 'PreparationReport'),
    'RegionSelectorSpec': ('geoai_simkit.pipeline.specs', 'RegionSelectorSpec'),
    'StageSpec': ('geoai_simkit.pipeline.specs', 'StageSpec'),
    'StructureGeneratorSpec': ('geoai_simkit.pipeline.specs', 'StructureGeneratorSpec'),
    'register_structure_generator': ('geoai_simkit.pipeline.structures', 'register_structure_generator'),
    'registered_structure_generators': ('geoai_simkit.pipeline.structures', 'registered_structure_generators'),
    'resolve_registered_structure_generator': ('geoai_simkit.pipeline.structures', 'resolve_registered_structure_generator'),
    'AnalysisCaseValidator': ('geoai_simkit.pipeline.validation', 'AnalysisCaseValidator'),
    'CaseValidationReport': ('geoai_simkit.pipeline.validation', 'CaseValidationReport'),
    'ValidationIssue': ('geoai_simkit.pipeline.validation', 'ValidationIssue'),
    'RegionAdjacencyInfo': ('geoai_simkit.pipeline.adjacency', 'RegionAdjacencyInfo'),
    'RegionBoundaryAdjacencyInfo': ('geoai_simkit.pipeline.adjacency', 'RegionBoundaryAdjacencyInfo'),
    'adjacency_summary_rows': ('geoai_simkit.pipeline.adjacency', 'adjacency_summary_rows'),
    'compute_region_adjacency': ('geoai_simkit.pipeline.adjacency', 'compute_region_adjacency'),
    'compute_region_boundary_adjacency': ('geoai_simkit.pipeline.adjacency', 'compute_region_boundary_adjacency'),
    'InterfaceReadyReport': ('geoai_simkit.pipeline.interface_ready', 'InterfaceReadyReport'),
    'apply_interface_node_split': ('geoai_simkit.pipeline.interface_ready', 'apply_interface_node_split'),
    'InterfaceFaceElementGroup': ('geoai_simkit.pipeline.interface_elements', 'InterfaceFaceElementGroup'),
    'InterfaceFaceElementPreview': ('geoai_simkit.pipeline.interface_elements', 'InterfaceFaceElementPreview'),
    'InterfaceFaceElementSnapshot': ('geoai_simkit.pipeline.interface_elements', 'InterfaceFaceElementSnapshot'),
    'compute_interface_face_elements': ('geoai_simkit.pipeline.interface_elements', 'compute_interface_face_elements'),
    'interface_element_definition_summary_rows': ('geoai_simkit.pipeline.interface_elements', 'interface_element_definition_summary_rows'),
    'interface_face_element_summary_rows': ('geoai_simkit.pipeline.interface_elements', 'interface_face_element_summary_rows'),
    'interface_face_group_summary_rows': ('geoai_simkit.pipeline.interface_elements', 'interface_face_group_summary_rows'),
    'materialize_interface_face_definitions': ('geoai_simkit.pipeline.interface_elements', 'materialize_interface_face_definitions'),
    'ContactAssemblyRow': ('geoai_simkit.pipeline.contact_materializer', 'ContactAssemblyRow'),
    'MaterializedContactRow': ('geoai_simkit.pipeline.contact_materializer', 'MaterializedContactRow'),
    'build_contact_solver_assembly_table': ('geoai_simkit.pipeline.contact_materializer', 'build_contact_solver_assembly_table'),
    'materialize_interface_requests': ('geoai_simkit.pipeline.contact_materializer', 'materialize_interface_requests'),
    'penalty_contact_triplets_for_submesh': ('geoai_simkit.pipeline.contact_materializer', 'penalty_contact_triplets_for_submesh'),
    'InterfaceMaterializationRequest': ('geoai_simkit.pipeline.interface_requests', 'InterfaceMaterializationRequest'),
    'build_interface_materialization_requests': ('geoai_simkit.pipeline.interface_requests', 'build_interface_materialization_requests'),
    'build_interface_materialization_request_payload': ('geoai_simkit.pipeline.interface_requests', 'build_interface_materialization_request_payload'),
    'build_stage_interface_activation_plan': ('geoai_simkit.pipeline.stage_interface_plan', 'build_stage_interface_activation_plan'),
    'apply_stage_interface_activation_plan': ('geoai_simkit.pipeline.stage_interface_plan', 'apply_stage_interface_activation_plan'),
    'register_interface_generator': ('geoai_simkit.pipeline.interfaces', 'register_interface_generator'),
    'registered_interface_generators': ('geoai_simkit.pipeline.interfaces', 'registered_interface_generators'),
    'resolve_registered_interface_generator': ('geoai_simkit.pipeline.interfaces', 'resolve_registered_interface_generator'),
    'RegionBoundarySurfaceSummary': ('geoai_simkit.pipeline.surfaces', 'RegionBoundarySurfaceSummary'),
    'RegionSurfaceInterfaceCandidate': ('geoai_simkit.pipeline.surfaces', 'RegionSurfaceInterfaceCandidate'),
    'compute_region_boundary_surfaces': ('geoai_simkit.pipeline.surfaces', 'compute_region_boundary_surfaces'),
    'compute_region_surface_interface_candidates': ('geoai_simkit.pipeline.surfaces', 'compute_region_surface_interface_candidates'),
    'interface_candidate_summary_rows': ('geoai_simkit.pipeline.surfaces', 'interface_candidate_summary_rows'),
    'region_surface_summary_rows': ('geoai_simkit.pipeline.surfaces', 'region_surface_summary_rows'),
    'InterfaceNodeSplitPlan': ('geoai_simkit.pipeline.topology', 'InterfaceNodeSplitPlan'),
    'InterfaceTopologyInfo': ('geoai_simkit.pipeline.topology', 'InterfaceTopologyInfo'),
    'InterfaceTopologySnapshot': ('geoai_simkit.pipeline.topology', 'InterfaceTopologySnapshot'),
    'analyze_interface_topology': ('geoai_simkit.pipeline.topology', 'analyze_interface_topology'),
    'interface_node_split_summary_rows': ('geoai_simkit.pipeline.topology', 'interface_node_split_summary_rows'),
    'interface_topology_summary_rows': ('geoai_simkit.pipeline.topology', 'interface_topology_summary_rows'),
}


def __getattr__(name: str) -> Any:
    if name not in _LAZY_EXPORTS:
        raise AttributeError(f"module 'geoai_simkit.pipeline' has no attribute {name!r}")
    module_name, attr_name = _LAZY_EXPORTS[name]
    module = import_module(module_name)
    value = getattr(module, attr_name)
    globals()[name] = value
    return value


__all__ = list(_LAZY_EXPORTS)
