from __future__ import annotations

"""Stable module interoperability contracts.

Only dependency-light DTOs, protocols and registries are exported here.  Modules
and services should prefer these contracts over importing another subsystem's
internal implementation objects.
"""

from .boundary import ImportBoundaryRule, ImportBoundaryViolation, ModuleBoundaryAuditReport, ModuleGovernanceReport
from .contact import ContactIterationReport, ContactMaterialParameters, ContactPairState, ContactSolverReport, InterfaceKinematics
from .geology import GeologyImportPayload, GeologyImporter, GeologySource
from .geometry import GeometryBuildRequest, GeometryBuildResult, GeometryBuilder
from .gui import GuiFileSlimmingMetric, GuiSlimmingReport
from .geotechnical import AnalysisReadinessSummary, BoundaryConditionSummary, InterfaceSummary, LoadSummary, MaterialMappingSummary, SolidMeshSummary, StageActivationSummary, analysis_readiness_summary, boundary_condition_summary, interface_summary, load_summary, material_mapping_summary, solid_mesh_summary, stage_activation_summary
from .material import MaterialModelProvider, MaterialModelProviderRegistry, MaterialModelRequest, MaterialModelResult
from .payloads import JsonMap, JsonScalar, MaterialMappingPayload, MeshPayload, PluginRegistrationPayload, QualityGatePayload, SolverInputPayload, SolverOutputPayload, WorkflowArtifactPayload
from .nonlinear import CutbackRecord, LoadIncrement, NewtonIterationReport, NonlinearSolverCoreReport, PlasticStateSnapshot, ReturnMappingResult
from .optimization import ModuleOptimizationMetric, ModuleOptimizationPlan, ModuleOptimizationReadinessReport, ModuleOptimizationStep, ModuleOptimizationTarget
from .meshing_validation import InterfaceConformityReport, OptionalMesherDependencyStatus, ProductionMeshingValidationReport, RegionMeshQualitySummary, STLRepairAction, STLRepairReport
from .modularity import CompleteModularizationReport, LegacyBoundaryMarker, ModuleDependencyEdge, ModuleInterfaceContract, ModuleLayerSpec, ModuleManifest
from .mesh import MeshGenerator, MeshGeneratorRegistry, MeshRequest, MeshResult, SOLID_CELL_TYPES, SURFACE_CELL_TYPES, SolidAnalysisReadinessIssue, SolidAnalysisReadinessReport
from .registry import KeyedPlugin, PluginCapability, PluginDependencyStatus, PluginDescriptor, PluginHealth, PluginRegistry, describe_plugin, normalize_plugin_capability
from .quality import ElementQualityMetric, GeotechnicalQualityGateReport, MaterialCompatibilityReport, MeshQualityGateReport, QualityGateIssue
from .plugins import ExternalPluginEntryPoint, ExternalPluginGroupSpec, ExternalPluginLoadIssue, ExternalPluginLoadRecord, ExternalPluginLoadReport
from .project import ProjectCompiledPhaseSummary, ProjectContext, ProjectGeometrySummary, ProjectMaterialSummary, ProjectMeshSummary, ProjectMutation, ProjectPortCapabilities, ProjectReadPort, ProjectRepository, ProjectResourceSummary, ProjectResultStoreSummary, ProjectSnapshot, ProjectStageSummary, ProjectTransaction, ProjectWritePort, is_project_port, project_compiled_phase_summary, project_document_from, project_geometry_summary, project_material_summary, project_mesh_summary, project_port_capabilities, project_result_store_summary, project_stage_summary
from .project_state import ProjectBoundaryState, ProjectEngineeringState, ProjectGeometryState, ProjectInterfaceState, ProjectMaterialState, ProjectResultState, ProjectSolidMeshState, ProjectStageState, project_engineering_state
from .results import PostProcessor, ResultRequest, ResultSink, ResultSummary
from .runtime import RuntimeBundlePayload, RuntimeBundleStore, RuntimeCompileRequest, RuntimeCompilerBackend
from .solver import SolveRequest, SolveResult, SolverBackend, SolverBackendRegistry, SolverCapabilities
from .stage import StageCompileRequest, StageCompileResult, StageCompiler
from .workflow import MeshWorkflowArtifact, ProjectWorkflowRequest, ProjectWorkflowReport, ResultWorkflowArtifact, SolveWorkflowArtifact, StageWorkflowArtifact, WorkflowArtifactLineage, WorkflowArtifactManifest, WorkflowArtifactRef, WorkflowStepReport, workflow_artifact_manifest_from_refs, workflow_artifact_ref_from_payload

__all__ = [
    "ContactIterationReport",
    "ContactMaterialParameters",
    "ContactPairState",
    "ContactSolverReport",
    "InterfaceKinematics",
    "ImportBoundaryRule",
    "ImportBoundaryViolation",
    "ModuleBoundaryAuditReport",
    "ModuleGovernanceReport",
    "GeologyImportPayload",
    "GeologyImporter",
    "GeologySource",
    "GuiFileSlimmingMetric",
    "GuiSlimmingReport",
    "AnalysisReadinessSummary",
    "BoundaryConditionSummary",
    "InterfaceSummary",
    "LoadSummary",
    "MaterialMappingSummary",
    "SolidMeshSummary",
    "StageActivationSummary",
    "analysis_readiness_summary",
    "boundary_condition_summary",
    "interface_summary",
    "load_summary",
    "material_mapping_summary",
    "solid_mesh_summary",
    "stage_activation_summary",
    "GeometryBuildRequest",
    "GeometryBuildResult",
    "GeometryBuilder",
    "CompleteModularizationReport",
    "LegacyBoundaryMarker",
    "ModuleDependencyEdge",
    "ModuleInterfaceContract",
    "ModuleLayerSpec",
    "ModuleManifest",
    "MaterialModelProvider",
    "MaterialModelProviderRegistry",
    "MaterialModelRequest",
    "MaterialModelResult",
    "MeshGenerator",
    "MeshGeneratorRegistry",
    "MeshRequest",
    "MeshResult",
    "SolidAnalysisReadinessReport",
    "SolidAnalysisReadinessIssue",
    "SURFACE_CELL_TYPES",
    "SOLID_CELL_TYPES",
    "QualityGateIssue",
    "MeshQualityGateReport",
    "MaterialCompatibilityReport",
    "GeotechnicalQualityGateReport",
    "InterfaceConformityReport",
    "OptionalMesherDependencyStatus",
    "ProductionMeshingValidationReport",
    "RegionMeshQualitySummary",
    "STLRepairAction",
    "STLRepairReport",

    "ExternalPluginEntryPoint",
    "ExternalPluginGroupSpec",
    "ExternalPluginLoadIssue",
    "ExternalPluginLoadRecord",
    "ExternalPluginLoadReport",
    "ElementQualityMetric",
    "CutbackRecord",
    "LoadIncrement",
    "NewtonIterationReport",
    "NonlinearSolverCoreReport",
    "PlasticStateSnapshot",
    "ReturnMappingResult",
    "ModuleOptimizationMetric",
    "ModuleOptimizationPlan",
    "ModuleOptimizationReadinessReport",
    "ModuleOptimizationStep",
    "ModuleOptimizationTarget",
    "JsonMap",
    "JsonScalar",
    "MaterialMappingPayload",
    "MeshPayload",
    "PluginRegistrationPayload",
    "QualityGatePayload",
    "SolverInputPayload",
    "SolverOutputPayload",
    "WorkflowArtifactPayload",
    "KeyedPlugin",
    "PluginDescriptor",
    "normalize_plugin_capability",
    "describe_plugin",
    "PluginHealth",
    "PluginDependencyStatus",
    "PluginCapability",
    "PluginRegistry",
    "PostProcessor",
    "project_engineering_state",
    "ProjectStageState",
    "ProjectSolidMeshState",
    "ProjectResultState",
    "ProjectMaterialState",
    "ProjectInterfaceState",
    "ProjectGeometryState",
    "ProjectEngineeringState",
    "ProjectBoundaryState",
    "ProjectContext",
    "ProjectStageSummary",
    "ProjectResultStoreSummary",
    "ProjectMeshSummary",
    "ProjectMaterialSummary",
    "ProjectGeometrySummary",
    "ProjectCompiledPhaseSummary",
    "ProjectMutation",
    "ProjectPortCapabilities",
    "ProjectReadPort",
    "ProjectRepository",
    "ProjectSnapshot",
    "is_project_port",
    "project_document_from",
    "project_stage_summary",
    "project_result_store_summary",
    "project_mesh_summary",
    "project_material_summary",
    "project_geometry_summary",
    "project_compiled_phase_summary",
    "project_port_capabilities",
    "ProjectResourceSummary",
    "ProjectTransaction",
    "ProjectWritePort",
    "ResultRequest",
    "ResultSink",
    "ResultSummary",
    "RuntimeBundlePayload",
    "RuntimeBundleStore",
    "RuntimeCompileRequest",
    "RuntimeCompilerBackend",
    "SolveRequest",
    "SolveResult",
    "SolverBackend",
    "SolverBackendRegistry",
    "SolverCapabilities",
    "StageCompileRequest",
    "StageCompileResult",
    "StageCompiler",
    "MeshWorkflowArtifact",
    "ResultWorkflowArtifact",
    "SolveWorkflowArtifact",
    "StageWorkflowArtifact",
    "WorkflowArtifactLineage",
    "WorkflowArtifactManifest",
    "workflow_artifact_manifest_from_refs",
    "WorkflowArtifactRef",
    "workflow_artifact_ref_from_payload",
    "ProjectWorkflowRequest",
    "ProjectWorkflowReport",
    "WorkflowStepReport",
]
